PREPARING DATASET


In [3]:
import numpy as np
import pandas as pd
import random as rnd
import math

In [117]:
GoodClg=[1 if x%5!=0 else 0 for x in range(30) ]
GoodClg=np.array(GoodClg)
GoodClg

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1])

In [118]:
Number_Intern=[rnd.randint(1,3) for i in range(30)]
Number_Intern=np.array(Number_Intern)
print(Number_Intern)
#[1, 3, 1, 1, 3, 3, 3, 1, 1, 2, 3, 1, 3, 2, 2, 1, 2, 1, 1, 2, 1, 1, 3,
      # 3, 2, 2, 1, 2, 3, 3]


array([1, 3, 1, 1, 3, 3, 3, 1, 1, 2, 3, 1, 3, 2, 2, 1, 2, 1, 1, 2, 1, 1, 3,
       3, 2, 2, 1, 2, 3, 3])

In [119]:
GoodPrj=[]
for x in range(30):
    if GoodClg[x]==1:
        if Number_Intern[x]>2:
            GoodPrj.append(1)
        else:
            GoodPrj.append(0)
    else:
        if Number_Intern[x]==1:
            GoodPrj.append(0)
        else:
            GoodPrj.append(1)
            
GoodPrj=np.array(GoodPrj)        
for i in range(5):
    x=rnd.randint(0,29)
    if GoodPrj[x]==1:
        GoodPrj[x]=0
    else:
        GoodPrj[x]=1
        
GoodPrj        
   #array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
    #   1, 0, 1, 0, 0, 0, 1])     

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1])

In [120]:
Num_Prj=[rnd.randint(1,3) for i in range(30)]
for i in range(30):
    if GoodPrj[i]==1 and Num_Prj[x]<3:
        Num_Prj[i]+=1
Num_Prj=np.array(Num_Prj)      
#array([1, 1, 3, 1, 2, 2, 3, 2, 1, 1, 2, 3, 1, 3, 1, 3, 1, 2, 2, 3, 2, 1, 3,
     #  1, 3, 2, 2, 3, 2, 1])
Num_Prj    

array([1, 1, 3, 1, 2, 2, 3, 2, 1, 1, 2, 3, 1, 3, 1, 3, 1, 2, 2, 3, 2, 1, 3,
       1, 3, 2, 2, 3, 2, 1])

In [121]:
Name=['a1', 'b1', 'c1', 'd1', 'e1', 'f1', 'g1', 'h1', 'i1', 'j1', 'k1', 'l1', 'm1', 'n1', 'o1', 'p1', 'q1', 'r1', 's1', 't1', 'u1', 'v1', 'w1', 'x1', 'y1', 'z1','a2','b2','c2','d2']
Name=np.array(Name)
Name

array(['a1', 'b1', 'c1', 'd1', 'e1', 'f1', 'g1', 'h1', 'i1', 'j1', 'k1',
       'l1', 'm1', 'n1', 'o1', 'p1', 'q1', 'r1', 's1', 't1', 'u1', 'v1',
       'w1', 'x1', 'y1', 'z1', 'a2', 'b2', 'c2', 'd2'],
      dtype='<U2')

In [125]:
Selected=[0,1,0,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,1,1,0,0,1,1,0,1,0,0,1,1]    
len(Selected)

30

In [2]:
class Student():
    def __init__(self):
        self.GC=0
        self.NI=0
        self.NP=0
        self.N=''
        self.GP=0
        self.Sno=0
        self.Slt=0
        
    def insert(self,gc,ni,np,n,gp,i,s):
        self.GC=gc
        self.NP=np
        self.NI=ni
        if i%5==0 and i%3==0:
            self.NI=ni+1
        if i%5==0 and i%2==0:
            self.NP=np+1
        self.N=n
        self.GP=gp
        self.Sno=i
        self.Slt=s
    def display(self):
        print('%02d' % self.Sno,end=" ") 
        print('   ',self.N,'   ',self.GC,'         ',self.NI,'     ',self.NP,'      ',self.GP,'        ',self.Slt)
    def GC(self):
        return int(GC.size)
    def NI(self):
        return int(NI.size)
    def NP(self):
        return int(NP.size)
    def GP(self):
        return int(GP.size)

In [130]:
df=[Student() for i in range(30)]
for x in range(30):
    df[x].insert(GoodClg[x],Number_Intern[x],Num_Prj[x],Name[x],GoodPrj[x],x+1,Selected[x])

print("SNO ","Name ","Good_Clg ","Num_Intern ","Num_Prj ","Good_Prj ","Selected ")    
for x in range(30):
    h=df[x]
    h.display()    
OLDgc=GoodClg.copy()    
OLDgp=GoodPrj.copy()    
OLDni=Number_Intern.copy()   
OLDnp=Num_Prj.copy()    
   

SNO  Name  Good_Clg  Num_Intern  Num_Prj  Good_Prj  Selected 
01     a1     0           1       1        0          0
02     b1     1           3       1        1          1
03     c1     1           1       3        0          0
04     d1     1           1       1        0          0
05     e1     1           3       2        1          1
06     f1     0           3       2        0          1
07     g1     1           3       3        1          1
08     h1     1           1       2        0          0
09     i1     1           1       1        0          0
10     j1     1           2       2        0          1
11     k1     0           3       2        0          1
12     l1     1           1       3        1          1
13     m1     1           3       1        1          0
14     n1     1           2       3        0          1
15     o1     1           3       1        1          0
16     p1     0           1       3        0          1
17     q1     1           2       1       

END OF DATASET
________________________________________________________________________________________________________________________________


DECISION TREE CODE

In [9]:
class Node:
    def __init__(self):
        self.Ycount=0
        self.Ncount=0
        self.nextFtr=None
        self.preFtr=None
        self.major=None
        self.isPure=False
        self.entropy=None
        self.data=None
        
    def initialize(self,yc,nc,pf):
        self.Ycount=yc
        self.Ncount=nc
        self.preFtr=pf
        self.major=(yc if yc>nc else nc)
        self.isPure=self.checkIsPure()
        self.entropy=self.calcEntropy()
    
    def checkIsPure(self):
        if self.Ycount!=self.Ncount and self.Ncount==0 :
            return True
        elif self.Ycount!=self.Ncount and self.Ycount==0 :
            return True
        else:
            return False
        
    def calcEntropy(self):
        pa=self.Ycount/(self.Ycount+self.Ncount)
        pb=self.Ncount/(self.Ycount+self.Ncount)
        logPa=math.log(pa,2)
        logPb=math.log(pb,2)
        paLogPa=-(pa*logPa)
        pbLogPb=-(pb*logPb)
        ey=paLogPa+pbLogPb
        return ey


In [8]:
class FtrNode:
    def __init__(self):
        self.FtrName=None
        self.limit=None
        self.yes=None
        self.no=None
        self.prnt=None
    def initialize(self,nm,lmt):
        self.FtrName=nm
        self.limit=lmt
    def split(self,prnt,yes,no):
        self.prnt=prnt
        self.yes=yes
        self.no=no
    def statsReturner(self,node):
        yy=0
        yn=0
        nn=0
        for i in range(int(node.data.size)):
            if node.data[i].getattr(Student,self.FtrName)<self.limit  :
                if node.data[i].Slt==1:
                    ny+=1
                else :
                    nn+=1
            else :
                if node.data[i].Slt==0:
                    yy+=1
                else :
                    yn+=1
                
        return [yy,yn,ny,nn]      
    
            

In [ ]:
FtrList=[]

FtrD={}

In [7]:
def calcPseudoEpy(Y,N):
        pa=Y/(Y+N)
        pb=N/(Y+N)
        logPa=math.log(pa,2)
        logPb=math.log(pb,2)
        paLogPa=-(pa*logPa)
        pbLogPb=-(pb*logPb)
        ey=paLogPa+pbLogPb
        return ey
def infoGain(yy,yn,ny,nn,Eo):
    sumAll=yy+yn+ny+nn
    e1=calcPseudoEpy(yy,yn)
    e2=calcPseudoEpy(ny,nn)
    e1=((yy+yn)/sumAll)*e1
    e2=((nn+ny)/sumAll)*e2
    En=e1+e2
    ig=Eo-En
    return ig

In [6]:
def splitter(node,idx):
    if node.isPure :
        return None
    elif idx==len(FtrD):
        ret=max(FtrD,key=int)
        return FtrD[ret]             
    else:
        curF=FtrList[idx]
        l=curF.statsReturner(node)
        yy,yn,ny,nn=l[0],l[1],l[2],l[3]
        IG=infoGain(yy,yn,ny,nn,node.entropy)
        FtrD[IG]=curF.FtrName
        return splitter(node,idx+1)
        
def treeMaker(): 
    ftr=splitter(root,0)
    for i in range(len(FtrList)):
        if FtrList[i].FtrName==ftr:
            feature=FtrList[i]
            FtrList.remove(FtrList[i])
        if feature!=None:
            node=Node
            node.initialize()
            
            
    
        
        
        
    